import React from 'react';
import { SeverityBadge } from '../common/Badge';
import { FileCheck2, Clock, MapPin, Radio, ShieldCheck } from 'lucide-react';

export function ResponsePlansView({ incidents = [], onSelectIncident }) {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-black text-slate-900 tracking-tight flex items-center gap-2">
          <span>Synthesized Response & Dispatch Plans</span>
          <span className="text-xs px-2 py-0.5 rounded-full bg-blue-50 text-blue-700 border border-blue-200 font-medium">
            {incidents.length} Active Plans
          </span>
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Tactical operational directives generated by the Dispatch Agent for field response units.
        </p>
      </div>

      {incidents.length === 0 ? (
        <div className="p-12 text-center bg-white rounded-xl border border-slate-200 text-slate-400 text-xs">
          No tactical response plans have been synthesized yet. Report an incident to generate plans.
        </div>
      ) : (
        <div className="space-y-4">
          {incidents.map((incident) => {
            const dispatch = incident.dispatch || {};
            const intake = incident.intake || {};
            const severity = incident.severity || {};
            const resources = incident.resources || [];
            const actionPlan = Array.isArray(dispatch.actionPlan) ? dispatch.actionPlan : [];

            return (
              <div
                key={incident.id}
                className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 space-y-4 hover:border-slate-300 transition"
              >
                {/* Header */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 pb-3">
                  <div className="flex items-center gap-3">
                    <div className="p-2 rounded-lg bg-blue-50 text-blue-600">
                      <FileCheck2 className="w-5 h-5" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-sm text-slate-900">
                          {intake.incidentType?.replace('_', ' ').toUpperCase() || 'EMERGENCY DISPATCH'}
                        </span>
                        <SeverityBadge severity={severity.severity} />
                      </div>
                      <div className="flex items-center gap-3 text-xs text-slate-500 mt-0.5">
                        <span className="flex items-center gap-1 font-medium">
                          <MapPin className="w-3 h-3 text-slate-400" />
                          {intake.location || 'Reported Scene'}
                        </span>
                        <span>·</span>
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3 text-slate-400" />
                          ETA: {dispatch.estimatedResponseTime || '10-15 mins'}
                        </span>
                      </div>
                    </div>
                  </div>

                  <button
                    onClick={() => onSelectIncident(incident)}
                    className="self-start sm:self-auto text-xs font-semibold px-3 py-1.5 rounded-lg bg-slate-900 text-white hover:bg-slate-800 transition"
                  >
                    View Full Incident
                  </button>
                </div>

                {/* Broadcast Message */}
                {dispatch.alertMessage && (
                  <div className="p-3 bg-blue-50/70 rounded-lg border border-blue-200/60 text-xs flex items-start gap-2">
                    <Radio className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                    <div>
                      <span className="font-semibold text-blue-900 block mb-0.5">Public Broadcast Alert:</span>
                      <p className="text-blue-950 font-medium">"{dispatch.alertMessage}"</p>
                    </div>
                  </div>
                )}

                {/* Tactical Steps */}
                <div className="space-y-1.5">
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
                    Execution Steps ({actionPlan.length}):
                  </span>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                    {actionPlan.map((step, idx) => (
                      <div key={idx} className="flex items-start gap-2 text-xs p-2 rounded bg-slate-50 border border-slate-200/60 text-slate-700">
                        <span className="font-bold text-slate-900">{idx + 1}.</span>
                        <span>{step}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Assigned Resources Bar */}
                <div className="pt-2 border-t border-slate-100 flex flex-wrap items-center gap-2 text-xs">
                  <span className="text-slate-400 font-medium text-[11px]">Assigned Assets:</span>
                    {resources.map((r) => (
                      <span key={r.id} className="px-2 py-0.5 rounded bg-slate-100 border border-slate-200 font-medium text-slate-700 text-[11px]">
                        {r.name} {r.distanceKm != null ? `(${r.distanceKm} km)` : '(Regional)'}
                      </span>
                    ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
